stages:
  - build
  - deploy

build_images:
  stage: build
  image: docker:20.10.16

  services:
    - docker:20.10.16-dind

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_scrips:
    - docker login -u $REGISTRY_USER -p #REGISTRY_PASS

  script: -docker build -t thiagoZardo/nomeDoapp:1.0 app/.
    - docker push thiagozardo/nomeDoapp:1.0

deploy_gcp:
  stage: deploy_gcp

  before_script:
    - chmod 400 $SSH_KEY

  script:
    - ssh -o StrictHostChecking=no -i $SSH_KEY usuario@ssh_SERVER "sudo rm -rf ./kubernetes-projeto2-dio && sudo git clone git@gitlab.com:devzardo/kubernetes-projeto2-dio.git && cd kubernetes-projeto2-dio && sudo chmod +x ./scrips.sh && ./script.sh"
