apiVersion: apps/v1
kind: Deployment
metadata:
  name: projeto-2-dio
  labels:
    app: projeto-2-dio
spec:
  replicas: 3
  selector:
    matchLabels: projeto-2-dio
  template:
    metadata:
      labels:
        app: projeto-2-dio
    spec:
      container:
        - name: backend
          image: php:apache
          volumeMounts:
            - name: backend
              mountPath: /var/www/html
          ports:
            - containerPort: 80

        - name: frontend
          image: nginx:latest
          volumeMounts:
            - name: frontend
              mountPath: /usr/share/nginx/html
          ports:
            - containerPort: 8080
          command: ["/bin/sh", "-c", "cp -r /usr/share/nginx/html/* /var/www/html && nginx -g 'daemon off;'"]
      ports:
        - containerPort: 80
