apiVersion: v1
kind: Service
metadata:
  name: lb-projeto-2-dio
  labels:
    app: app-html-lb
spec:
  selector:
    app: projeto-2-dio
  type: LoadBalancer
  ports:
    - name: mysql-storage
      protocol: TCP
      port: 3306
      targetPort: 3306
    - name: backend
      protocol: TCP
      port: 80
      targetPort: 80
    - name: frontend
      protocol: TCP
      port: 8080
      targetPort: 8080
